import smtplib
import time
from email.message import EmailMessage


class EmailAlertManager:
    def __init__(self, config):
        self.config = config
        self.last_alert_time = 0

    def can_send(self):
        return time.time() - self.last_alert_time >= self.config.ALERT_COOLDOWN

    def send(self, alert_time, ip, method, path, status, total_requests,
             current_ip_count, risk_score, reasons):
        message = EmailMessage()
        message["Subject"] = " HIGH RISK TRAFFIC DETECTED"
        message["From"] = self.config.SENDER_EMAIL
        message["To"] = self.config.RECEIVER_EMAIL
        reason_text = "\n".join(f"- {reason}" for reason in reasons)
        message.set_content(f""" HIGH RISK HTTP TRAFFIC DETECTED

Time: {alert_time}

IP Address: {ip}
Method: {method}
Path: {path}
Status: {status}

Total Requests in {self.config.WINDOW_SIZE}s: {total_requests}
Requests From IP: {current_ip_count}

Risk Score: {risk_score}

Reasons:
{reason_text}

This alert was generated by your
Real-Time HTTP Traffic Monitor.
""")

        if not self.config.APP_PASSWORD:
            print(" DDOS_MONITOR_APP_PASSWORD is not set.")
            return False

        try:
            with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=10) as smtp:
                smtp.login(self.config.SENDER_EMAIL, self.config.APP_PASSWORD)
                smtp.send_message(message)
            print(" Email alert sent successfully!")
            self.last_alert_time = time.time()
            return True
        except Exception as error:
            print(" Failed to send email alert:")
            print(error)
            return False
